.PHONY: test-utils test-expr test-compile test-inst test-dual test-main

all: test-utils test-expr test-compile test-inst test-dual test-main


test-utils:
	raco test test-utils.rkt
test-expr:
	raco test test-expr.rkt
test-compile:
	raco test test-compile.rkt
test-inst:
	raco test test-inst.rkt
test-dual:
	raco test test-dual.rkt
test-main:
	raco test test-eval.rkt
