.PHONY: expr compile inst dual main

all: expr compile inst dual main

expr:
	raco test test-expr.rkt
compile:
	raco test test-compile.rkt
inst:
	raco test test-inst.rkt
dual:
	raco test test-dual.rkt
main:
	raco test test-main.rkt
